FROM ruby:3.4.5

# 必要なライブラリをインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev

# 作業ディレクトリ
WORKDIR /app

# bundler をインストール
RUN gem install bundler

# Gemfile をコピーして依存関係をインストール
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーション全体をコピー
COPY . .

# ポート
EXPOSE 3000

# デフォルトコマンド
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
